### ISSUE TITLE
Daylight savings time

### ISSUE THREAD

**Issue by Ralins** [Auction-Sniper/Auction-Sniper#12]
Hi, the program currently is not working with the time change

**Comment by Tsunamibeach** [comment]
same problem. thanks

**Comment by mtriplett1** [comment]
Same here. Just missed 2 auctions.

**Comment by fun2drum** [comment]
Has this been fixed?  I just downloaded the app today and I now have several auctions set up.  I'd hate to miss them due to a glitch like that.

**Comment by fun2drum** [comment]
I just looked at the end time on a couple of my auctions and it's exactly an hour after the end time on SGW's site.  Thanks for bringing it to my attention - I might have missed a couple of good ones.  I hope it's an easy and fast fix because I was excited about using this app.

**Comment by Auction-Sniper** [comment]
Hi, the daylight savings time bug with the shopgoodwill sniper has now been fixed in the latest version released today version 23.5.321 which is available for download in the Windows Store here:

[https://apps.microsoft.com/store/detail/shopgoodwill-auction-sniper/9N9ZLL527KQ1](https://apps.microsoft.com/store/detail/shopgoodwill-auction-sniper/9N9ZLL527KQ1)

**Comment by Auction-Sniper** [comment]
Closing this since new version solved bug and no more activity.

**Comment by fun2drum** [comment]
What about for Mac?  It’s no longer available on the App Store.  Thanks
Gary


Gary Walker


From: Auction-Sniper ***@***.***>
Date: Thursday, May 4, 2023 at 12:55 PM
To: Auction-Sniper/Auction-Sniper ***@***.***>
Cc: fun2drum ***@***.***>, Comment ***@***.***>
Subject: Re: [Auction-Sniper/Auction-Sniper] Daylight savings time (Issue #12)

Hi, the daylight savings time bug with the shopgoodwill sniper has now been fixed in the latest version released today version 23.5.321 which is available for download in the Windows Store here:

https://apps.microsoft.com/store/detail/shopgoodwill-auction-sniper/9N9ZLL527KQ1

**Comment by Auction-Sniper** [comment]
We are currently working on the Mac version update now, we should have the Mac update released within the next week or so as well...

**Comment by fun2drum** [comment]
That’s great to hear!  Please keep me posted.
Gary

Gary Walker

________________________________

**Comment by Auction-Sniper** [comment]
Hi Gary,

We have finally released the Mac version of the auction sniper and you can now download it here:

[https://github.com/Auction-Sniper/ShopGoodwill](https://github.com/Auction-Sniper/ShopGoodwill)
