### ISSUE TITLE
Is Auction Sniper for Shopgoodwill dead??

### ISSUE THREAD

**Issue by bjwhitely** [Auction-Sniper/Auction-Sniper#25]
Both "snipeable.exe" and "ShopGoodwill Auction Sniper.exe" have stopped working. Tried downloading "new" Windows version at https://github.com/Auction-Sniper/ShopGoodwill and get error:
{
  "error": {
    "code": 404,
    "message": "File not found: 1-9FD4uBZt2pcj8dkMhWv3qiaQborurNH.",
    "errors": [
      {
        "message": "File not found: 1-9FD4uBZt2pcj8dkMhWv3qiaQborurNH.",
        "domain": "global",
        "reason": "notFound",
        "location": "fileId",
        "locationType": "parameter"
      }
    ]
  }
}

**Comment by Auction-Sniper** [comment]
Hi bjwhitely,

It seems that our download server was down when you tried please try clicking refresh on our homepage and the download  links should be updated now.

Please let us know if you need any further assistance!

Best Regards,
Customer Service

**Comment by Auction-Sniper** [comment]
I am closing this thread since there has been no response from you bjwhitely, for further reference, you can always download the latest version of auction sniper and shopgoodwill sniper from our website at http://Snipeable.com or http://SGWSniper.com

Please let us know if we can be of further assistance!

Thank you,
Customer Service
