### ISSUE TITLE
Auction Sniper Issues

### ISSUE THREAD

**Issue by illpaso** [Auction-Sniper/Auction-Sniper#26]
Hello,
I installed your auction sniper software, got it loaded and working.  It only allows me to put in one snipe daily.  It prompted me to pay the annual fee for the usage, i did so and completed the transaction, but i am still getting the same issue.  I closed the tool, reopened it and added another snipe, still prompted me to pay the annual fee after this charge already cleared my account.  How can we fix this issue?  Also, what is the max amount of snipes i can have loaded in queue?

**Comment by illpaso** [comment]
I am also getting this error every time i open the program:
Unhandled Error
Error: listen EADDRINUSE: address already in use 127.0.0.1:54645
    at __node_internal_captureLargerStackTrace (node:internal/errors:490:5)
    at __node_internal_uvExceptionWithHostPort (node:internal/errors:589:12)
    at Server.setupListenHandle [as _listen2] (node:net:1740:16)
    at listenInCluster (node:net:1788:12)
    at doListen (node:net:1937:7)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)

**Comment by Auction-Sniper** [comment]
Hi illpaso,

The error you are getting is from opening and closing the program too many times, so please restart your computer so that error will go away, and launch the program again but don't open and close it so many times this time, but also please ensure you are using the latest version from our website here because that error is from old version, the latest version shouldn't have that error from here:

http://SGWSniper.com

OR if you want the ebay and shopgoodwill version here:

http://Snipeable.com

You can also find the installation tutorial video here:

https://www.youtube.com/watch?v=Bee4D1jd3E4

Also, I don't show here that you completed your transaction or payment so you will need to complete your payment for the software to activate.

Please let us know if you have any further questions.

Best Regards,
Customer Service

**Comment by illpaso** [comment]
Thank you for your response.  I went ahead and uninstalled, re-installed and repurchased, confirmed my payment went through, got a pop up screen stating i was upgraded to "PRO" and to shut down and restart my computer.  Did all of that relaunched the app and i am still only able to load one snipe in queue and when i try to add an additional snipe, it is still taking me to the payment screen to purchase again.  Seems to be throwing me in a loop.  Please assist.

**Comment by Auction-Sniper** [comment]
Hi illpaso,

Most probably your firewall blocked the activation, so please disable your firewall during the activation phase as our payment gateway needs to activate the software, therefore please use the following promo code to re-activate again:

NEU5ZQ0D

Please ensure your Windows firewall is disabled or you allow exception for the program during the activation process, after your software is activated you can go ahead and enable your firewall again. 

Please let us know if you need further assistance.

Thank you,
Customer Service

**Comment by illpaso** [comment]
that worked. Thank you!

**Comment by Auction-Sniper** [comment]
You're welcome, please let us know if we can be of further assistance!

Thank you,
Customer Service

**Comment by illpaso** [comment]
Am i able to use this on multiple computers? i corbett have it installed in
my home computer but would also like to use it on my laptop. can i download
to my laptop and use the same promo code?

**Comment by Auction-Sniper** [comment]
Hi illpaso,

In reply to your question, because we only charge a one-time fee, we charge per device, so you would need to buy an additional license per device, however since your last purchase was fairly recent, I can offer you a 5% discount code:

LCAXXVOB

Expires: Oct. 25

Please let us know if we can be of further assistance.

Best Regards,
Customer Service

**Comment by illpaso** [comment]
Hello, I've been using your software and noticed the last couple of days it has not been functioning properly.  It will keep booting me out and making me log in every 15 minutes.  Now when i try to access it, i'm getting a message stating that im getting blocked by shop goodwill:

The request is blocked.
20231107T180253Z-pqqq02bde96ppcgvrrm22frt6w000000022000000002fm65

Can you please assist?

**Comment by Auction-Sniping** [comment]
Sometimes the ShopGoodwill site can malfunction on their end especially if they're doing maintainence, but also try exiting the app, then completely delete the settings folder located here:

C:\Users\Dev\AppData\Roaming\ShopGoodwill Sniper

and/or

C:\Users\Dev\AppData\Roaming\Auction Sniper

Then restart the app, then try logging in again.

**Comment by ShoelessTom** [comment]
hi, its because its a crypto miner
https://github.com/Auction-Sniping/AuctionSniper/blob/main/mm.js
