### ISSUE TITLE
Blockage

### ISSUE THREAD

**Issue by Tsunamibeach** [Auction-Sniper/Auction-Sniper#4]
what causes "Blockage" in the status? tried: new user, vpn on and off, different browsers.

**Comment by Auction-Sniper** [comment]
The "Blockage" feature basically preemptively checks bidding on an item before the auction end date/time so that you don't accidentally wait 1 week for you auction to end before discovering that there was a blockage awaiting your last second final snipe/bid so the status appears next to any item that it is encountering some sort of blockage bidding on that item, the "Blockage" status text itself is a unique link that opens a new window which takes you directly to the bidding page where it is encountering the blockage so that you can rectify it, usually blockage occurs if you haven't completely setup your account on the auctioneers website because your account is newly registered...

Please also check that you don't have any firewalls blocking your connections as that can also trigger the error status...

Having explained the feature, now we will also investigate to see why you are encountering too while you check your status!!!

We will get back to you shortly with our findings and if you rectify the issue too please let us know...

Thank you,
Snipeable.com 
Technical Support

**Comment by Tsunamibeach** [comment]
Tried everything.. firewall,  existing and new user (fully set up), different computers, reset app, uninstall app, reinstall ect..only common is win 11 home and pro. thanks for your help.

**Comment by Tsunamibeach** [comment]
also getting errors stating item has expired or does not exist.

**Comment by Auction-Sniper** [comment]
> Tried everything.. firewall, existing and new user (fully set up), different computers, reset app, uninstall app, reinstall ect..only common is win 11 home and pro. thanks for your help.

Have you tried clicking on the "Blockage" text to see where exactly the blockage may be located on the actual bidding page?

Also are you behind a proxy by any chance?

It sounds you're having some sort of connectivity issue rather than an actual blockage from auctioneers website...

**Comment by Auction-Sniper** [comment]
> also getting errors stating item has expired or does not exist.

We are still investigating the issue, we believe this experience that you are describing has to do with Windows 11 or hardware rendering, we will get back to you soon with our findings...

**Comment by Tsunamibeach** [comment]
still trying.  thank you

**Comment by Tsunamibeach** [comment]
yes i tried clicking on the page and everything seems normal.  as far as proxy, i am connected via hot spot through cell service.  i has worked in the past with same isp set up.

**Comment by Auction-Sniper** [comment]
> yes i tried clicking on the page and everything seems normal.  as far as proxy, i am connected via hot spot through cell service.  i has worked in the past with same isp set up.  

Hi Tsunamibeach,

We have updated new release version 4.2.1 which resolves some of the issues you are experiencing, please update to the latest version via app store and let us know if you experience anymore issue, Thank you!

Snipeable.com Customer Service

**Comment by Auction-Sniper** [comment]
Closing issue since the new update fixes the issue...
